config/routes.rb
Stractegize::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index,:show,:delete]

  resources :clients do
    resources :projects do
      resources :milestones
    end
    resources :libraries
    resources :action_items
    resources :contacts
  end

  resources :libraries

  resources :milestones

  resources :projects

  resources :action_items

  resources :contacts

  get 'pages/test' => 'pages#test'
  get 'pages/test2' => 'pages#test2'

  root 'projects#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :libraries, inverse_of: :client
  has_many :projects, inverse_of: :client
  has_many :contacts, inverse_of: :client
  has_many :action_items, inverse_of: :client

  belongs_to :user, inverse_of: :clients

  validates :user, presence: true
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :start_date, :user_id, :notes)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client, html: { role: "form" }) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.text_field :start_date, class: "form-control", :'data-provide' => "datepicker" %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, "Account Manager" %>
    <%= f.collection_select :user_id, User.all, :id, :full_name, { :prompt => "Select user" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <%= f.submit "Save Client", class: "btn btn-primary" %>
<% end %>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<%= render 'form' %>

app/views/clients/index.html.erb
<h1>Clients</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>User</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.start_date %></td>
        <td><%= client.user.full_name %></td>
        <td><%= client.notes %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Client', new_client_path, class: 'btn btn-primary' %>

app/views/clients/new.html.erb
<h1>New Client</h1>
<%= render 'form' %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @client.start_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @client.user.full_name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>