config/routes.rb
Stractegize::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index,:show,:delete]

  resources :clients do
    resources :projects do
      resources :milestones
    end
    resources :libraries
    resources :action_items
    resources :contacts
  end

  resources :libraries

  resources :milestones

  resources :projects

  resources :action_items

  resources :contacts

  get 'pages/test' => 'pages#test'
  get 'pages/test2' => 'pages#test2'

  root 'projects#index'

end

app/models/library.rb
class Library < ActiveRecord::Base

  belongs_to :client, inverse_of: :libraries
  belongs_to :user, inverse_of: :libraries

  validates :client, presence: true
  validates :user, presence: true

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    if !params[:client_id].blank?
      @libraries = Library.where(client_id: params[:client_id])
    else
      @libraries = Library.all
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render action: 'show', status: :created, location: @library }
      else
        format.html { render action: 'new' }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:document_name, :description, :document_type, :topic_id, :category_id, :client_id, :user_id)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_for(@library, html: { role: "form" }) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :document_name %>
    <%= f.text_field :document_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :document_type %>
    <%= f.text_field :document_type, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :topic_id %>
    <%= f.number_field :topic_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.number_field :category_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :client_id %>
    <%= f.collection_select :client_id, Client.all, :id, :name, { prompt: "Select client" }, { class: "form-control" }%>
  </div>
  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :full_name, { prompt: "Select user" }, { class: "form-control" } %>
  </div>
  <%= f.submit "Save Library", class: "btn btn-primary" %>
<% end %>

app/views/libraries/edit.html.erb
<h1>Edit Library</h1>
<%= render 'form' %>

app/views/libraries/index.html.erb
<h1>Libraries</h1>
<table class="table">
  <thead>
    <tr>
      <th>Document name</th>
      <th>Description</th>
      <th>Document type</th>
      <th>Topic</th>
      <th>Category</th>
      <th>Client</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.document_name %></td>
        <td><%= library.description %></td>
        <td><%= library.document_type %></td>
        <td><%= library.topic_id %></td>
        <td><%= library.category_id %></td>
        <td><%= library.client.name %></td>
        <td><%= library.user.full_name %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Library', new_library_path, class: "btn btn-primary" %>

app/views/libraries/new.html.erb
<h1>New Library</h1>
<%= render 'form' %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document name:</strong>
  <%= @library.document_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @library.description %>
</p>

<p>
  <strong>Document type:</strong>
  <%= @library.document_type %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @library.topic_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @library.category_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @library.client.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @library.user.full_name %>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>