config/routes.rb
Stractegize::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index,:show,:delete]

  resources :clients do
    resources :projects do
      resources :milestones
    end
    resources :libraries
    resources :action_items
    resources :contacts
  end

  resources :libraries

  resources :milestones

  resources :projects

  resources :action_items

  resources :contacts

  get 'pages/test' => 'pages#test'
  get 'pages/test2' => 'pages#test2'

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :client, inverse_of: :projects
  belongs_to :user, inverse_of: :projects
  belongs_to :creator, foreign_key: :created_by, class_name: 'User'

  has_many :milestones, inverse_of: :project
  has_many :action_items, inverse_of: :project

  validates :client, presence: true
  validates :user, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if !params[:client_id].blank?
      @projects = Project.where(client_id: params[:client_id])
    else
      @projects = Project.all
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.created_by = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :client_id, :user_id, :status, :system_status, :created_by)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def project_statuses
    [
      ['Not Started', 'Not Started'],
      ['On Track', 'On Track'],
      ['At Risk', 'At Risk'],
      ['Off Track', 'Off Track'],
      ['Blocked', 'Blocked']
    ]
  end

  def system_statuses
    [
      ['Active', 'Active'],
      ['Inactive', 'Inactive'],
      ['Complete', 'Complete'],
      ['Hold', 'Hold']
    ]
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project, html: { role: "form" }) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :client_id %>
    <%= f.collection_select :client_id, Client.all, :id, :name, { prompt: "Select client" }, { class: "form-control" }%>
  </div>
  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :full_name, { prompt: "Select user" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, options_for_select(project_statuses), { prompt: "Select status" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :system_status %>
    <%= f.select :system_status, options_for_select(system_statuses), { prompt: "Select system status" }, { class: "form-control" } %>
  </div>
  <%= f.submit "Save Project", class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Client</th>
      <th>User</th>
      <th>Status</th>
      <th>System status</th>
      <th>Created by</th>
      <th>Milestones</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.client.name %></td>
        <td><%= project.user.full_name %></td>
        <td><%= project.status %></td>
        <td><%= project.system_status %></td>
        <td><%= project.creator.full_name %></td>
	<td><%= link_to project.milestones.count, client_project_milestones_path(project.client, project) %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Client:</strong>
  <%= @project.client.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user.full_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>System status:</strong>
  <%= @project.system_status %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @project.creator.full_name %>
</p>
<p>
  <strong>Milestones:</strong>
</p>
<%= render partial: "milestones/table", locals: { milestones: @project.milestones } %>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>