config/routes.rb
Stractegize::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index,:show,:delete]

  resources :clients do
    resources :projects do
      resources :milestones
    end
    resources :libraries
    resources :action_items
    resources :contacts
  end

  resources :libraries

  resources :milestones

  resources :projects

  resources :action_items

  resources :contacts

  get 'pages/test' => 'pages#test'
  get 'pages/test2' => 'pages#test2'

  root 'projects#index'

end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base

  belongs_to :client, inverse_of: :action_items
  belongs_to :project, inverse_of: :action_items
  belongs_to :milestone, inverse_of: :action_items
  belongs_to :user, inverse_of: :action_items

  validates :user, presence: true
  validates :milestone, presence: true
  validates :project, presence: true
  validates :client, presence: true

end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  before_action :set_action_item, only: [:show, :edit, :update, :destroy]

  # GET /action_items
  # GET /action_items.json
  def index
    if !params[:client_id].blank?
      @action_items = ActionItem.where(client_id: params[:client_id])
    else
      @action_items = ActionItem.all
    end
  end

  # GET /action_items/1
  # GET /action_items/1.json
  def show
  end

  # GET /action_items/new
  def new
    @action_item = ActionItem.new
  end

  # GET /action_items/1/edit
  def edit
  end

  # POST /action_items
  # POST /action_items.json
  def create
    @action_item = ActionItem.new(action_item_params)

    respond_to do |format|
      if @action_item.save
        format.html { redirect_to @action_item, notice: 'Action item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @action_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_items/1
  # PATCH/PUT /action_items/1.json
  def update
    respond_to do |format|
      if @action_item.update(action_item_params)
        format.html { redirect_to @action_item, notice: 'Action item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.json
  def destroy
    @action_item.destroy
    respond_to do |format|
      format.html { redirect_to action_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_item
      @action_item = ActionItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_item_params
      params.require(:action_item).permit(:short_description, :details, :action_type, :process_id, :project_id, :milestone_id, :user_id, :due_date, :status, :notes, :client_id, :entered_by, :status_last_updated, :notes_last_updated)
    end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper

  def action_types
    [
      ['Action Item', 'Action Item'],
      ['Project Task', 'Project Task'],
      ['Project Milestone', 'Project Milestone'],
      ['Risk', 'Risk'],
      ['Process Task', 'Process Task']
    ]
  end

  def action_statuses
    [
      ['Not Started', 'Not Started'],
      ['In Progress', 'In Progress'],
      ['Hold', 'Hold'],
      ['Blocked', 'Blocked'],
      ['Completed', 'Completed'],
      ['Closed', 'Closed']
    ]
  end

end

app/views/action_items/_form.html.erb
<%= form_for(@action_item, html: { role: "form" }) do |f| %>
  <% if @action_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_item.errors.count, "error") %> prohibited this action_item from being saved:</h2>
      <ul>
      <% @action_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :short_description %><br>
    <%= f.text_field :short_description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :details %><br>
    <%= f.text_area :details, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :action_type %><br>
    <%= f.select :action_type, options_for_select(action_types), { prompt: "Select type" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :process_id %><br>
    <%= f.number_field :process_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :project_id %><br>
    <%= f.collection_select :project_id, Project.all, :id, :name, { prompt: "Select project" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :milestone_id %><br>
    <%= f.collection_select :milestone_id, Milestone.all, :id, :name, { prompt: "Select milestone" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :full_name, { prompt: "Select user" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :due_date %><br>
    <%= f.text_field :due_date, class: "form-control", :'data-provide' => "datepicker" %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(action_statuses), { prompt: "Select status" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :client_id %><br>
    <%= f.collection_select :client_id, Client.all, :id, :name, { prompt: "Select client" }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :entered_by %><br>
    <%= f.collection_select :entered_by, User.all, :id, :full_name, {prompt: "Select user"}, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :status_last_updated %><br>
    <%= f.text_field :status_last_updated, class: "form-control", :'data-provide' => "datepicker" %>
  </div>
  <div class="form-group">
    <%= f.label :notes_last_updated %><br>
    <%= f.text_field :notes_last_updated, class: "form-control", :'data-provide' => "datepicker" %>
  </div>
  <%= f.submit "Save Action Item", class: "btn btn-primary" %>
<% end %>

app/views/action_items/edit.html.erb
<h1>Edit Action Item</h1>
<%= render 'form' %>

app/views/action_items/index.html.erb
<h1>Action Items</h1>
<table class="table">
  <thead>
    <tr>
      <th>Short description</th>
      <th>Details</th>
      <th>Action type</th>
      <th>Process</th>
      <th>Project</th>
      <th>Milestone</th>
      <th>User</th>
      <th>Due date</th>
      <th>Status</th>
      <th>Notes</th>
      <th>Client</th>
      <th>Entered by</th>
      <th>Status last updated</th>
      <th>Notes last updated</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @action_items.each do |action_item| %>
      <tr>
        <td><%= action_item.short_description %></td>
        <td><%= action_item.details %></td>
        <td><%= action_item.action_type %></td>
        <td><%= action_item.process_id %></td>
        <td><%= action_item.project.name %></td>
        <td><%= action_item.milestone.name %></td>
        <td><%= action_item.user.full_name %></td>
        <td><%= action_item.due_date %></td>
        <td><%= action_item.status %></td>
        <td><%= action_item.notes %></td>
        <td><%= action_item.client.name %></td>
        <td><%= action_item.entered_by %></td>
        <td><%= action_item.status_last_updated %></td>
        <td><%= action_item.notes_last_updated %></td>
        <td><%= link_to 'Show', action_item %></td>
        <td><%= link_to 'Edit', edit_action_item_path(action_item) %></td>
        <td><%= link_to 'Destroy', action_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Action Item', new_action_item_path, class: "btn btn-primary" %>

app/views/action_items/new.html.erb
<h1>New Action Item</h1>
<%= render 'form' %>

app/views/action_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short description:</strong>
  <%= @action_item.short_description %>
</p>

<p>
  <strong>Details:</strong>
  <%= @action_item.details %>
</p>

<p>
  <strong>Action type:</strong>
  <%= @action_item.action_type %>
</p>

<p>
  <strong>Process:</strong>
  <%= @action_item.process_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @action_item.project.name %>
</p>

<p>
  <strong>Milestone:</strong>
  <%= @action_item.milestone.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @action_item.user.full_name %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @action_item.due_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @action_item.status %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @action_item.notes %>
</p>

<p>
  <strong>Client:</strong>
  <%= @action_item.client.name %>
</p>

<p>
  <strong>Entered by:</strong>
  <%= @action_item.entered_by %>
</p>

<p>
  <strong>Status last updated:</strong>
  <%= @action_item.status_last_updated %>
</p>

<p>
  <strong>Notes last updated:</strong>
  <%= @action_item.notes_last_updated %>
</p>

<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>